version: 0.2 

phases: 
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - npm test
    finally:
      - echo test completed
  build:
    commands:
      - npm run-script build
  post_build:
    commands:
      - echo build completed

artifacts:
  files:
    - index.js
    - package.json
    - node_modules