name: sns-backend
on: [push] 

jobs: 
  build:
    name: sns-backend build
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: module caching
        uses: actions/cache@v1
        with: 
          path: node_modules
          key: ${{ runner.OS}}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | 
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      
      - name: dependencies
        run: npm install 

      - name: tests
        run: npm test
      
      - name: build
        run: npm run build

      - name: packaging
        run: zip -r deploy.zip ./* -x "**node_modules**"

#      - name: deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v11
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: sns-v1
#          environment_name: dev
#          version_label: 1
#          region: ap-northeast-2
#          deployment_package: deploy.zip
